#!/bin/bash

# make sure we are in a git repository
if [ "`git rev-parse --is-inside-work-tree`" != "true" ]
then
	exit 1
fi

# get branch to use
BRANCH=''
CURRENT_BRANCH="`git rev-parse --abbrev-ref HEAD`"

# if no argument is supplied, try to use the current branch
if [ -z $1 ]
then
	BRANCH=$CURRENT_BRANCH
# otherwise, use the specified branch
else
	BRANCH=$1
	# Check to make sure specified branch exists
	if [ -z "`git show-ref $BRANCH`" ]
	then
		echo "fatal: Branch $BRANCH does not exist"
		exit 1
	fi
fi

# make sure we're up to date with remote
git svn-update

# reintegrate branch into master if necessary, and dcommit
if [ $BRANCH == 'master' ]
then
	git svn dcommit
else
	git checkout master && git rebase $BRANCH && git svn dcommit
fi
