#!/bin/bash

if [ "`git rev-parse --is-inside-work-tree`" != "true" ]
then
	exit 1
fi

# get branch to use
BRANCH=''

# if no argument is supplied, try to use the current branch
if [ -z $1 ]
then
	BRANCH="`git rev-parse --abbrev-ref HEAD`"
else
	BRANCH=$1
	# Check to make sure specified branch exists
	if [ -z "`git show-ref $BRANCH`" ]
	then
		echo "fatal: Branch $BRANCH does not exist"
		exit 1
	fi
fi

if [ $BRANCH == 'master' ]
then
	echo "Syncing branch master with remote"
	git checkout master && git svn rebase
else
	echo "Syncing branch $BRANCH and master with remote"
	git checkout master && git svn rebase && git checkout $BRANCH && git rebase master
fi
